SELECT T3.CORP_STD1_NAME -- Subsidiary Name
,T24.STRATEGIC_CITY_FLAG -- STRATEGIC_CITY_FLAG
,T24.STRATEGIC_CITY_NAME -- STRATEGIC_CITY_NAME
,T2.GSFS_REPAIR_HEADER_NO -- GSFS Receipt No*
,T21.DIVISION_ID -- Division Code
,T21.DIVISION_STD1_NAME -- Division Name
,T21.PRODUCT3_STD1_NAME -- Product3 Name
,CASE WHEN T19.PART_NO1 IS NULL THEN 'N' ELSE 'Y' END -- Parts Use Flag
,T8.SERVICE_CENTER_TYPE_NAME -- SVC Center Type
,T23.SHIP_TO_NAME -- Ship To Name
,T22.CUSTOMER_CODE -- Ship to Code
,T14.CUSTOMER_STD1_NAME -- Bill to Name
,RTRIM(T2.BILL_TO_CUSTOMER_CODE)
 
 
-- Bill to Code
,T9.SERVICE_ENGINEER_STD1_NAME -- SVC Engineer Name
,T1.SERVICE_ENGINEER_CODE -- SVC Engineer Code
,CASE WHEN T2.PRC_RECEIPT = 'PR' THEN T16.SUBSDR_WARRANTY_TYPE_ID ELSE T1.WARRANTY_FLAG END -- Warranty Flag
,T5.SVC_RECEIPT_TYPE_STD1_NAME -- SVC Receipt Type
,T15.SERVICE_TYPE_ID -- SVC Type Code
,T12.YYYY_ID -- Repair Receipt Year-YYYY
,T12.YYYYMM_ID -- Repair Receipt Month-YYYYMM
,T12.YYYYMMDD_ID -- Repair Receipt Date-YYYYMMDD
,FORMAT_DATETIME('%Y%m%d',T1.FIRST_PROMISE_TIMESTAMP) -- First Promise Date-YYYYMMDD
,T1.FIRST_PROMISE_TIMESTAMP -- First Promise Timestamp
,FORMAT_DATETIME('%Y%m%d',T1.PROMISE_TIMESTAMP) -- Promise Date-YYYYMMDD
,T1.PROMISE_TIMESTAMP -- Promise Timestamp
,T1.VISIT_CONFIRM_FLAG -- Visit Confirm Flag
,T1.VISIT_CONFIRM_DATE -- Visit Confirm Date
,T13.YYYY_ID -- Repair End Year-YYYY
,T13.YYYYMM_ID -- Repair End Month-YYYYMM
,T13.YYYYMMDD_ID -- Repair End Date-YYYYMMDD
,T11.YYYY_ID -- GERP Input Year-YYYY (Last)
,T11.YYYYMM_ID -- GERP Input Month-YYYYMM (Last)
,T2.ERP_CREATION_YYYYMMDD_ID -- GERP Input Date-YYYYMMDD ID (Last)
,T2.ERP_CREATION_TIMESTAMP -- GERP Input Timestamp (Last)
,T22.POSTAL_CODE -- Postal Code (Ship To)
,T14.POSTAL_CODE -- Postal Code (Bill To)
,CASE WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) = 0 THEN T4.POSTAL_CODE
     WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.POSTAL_CODE IS NULL THEN T4.POSTAL_CODE
     WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) > 0 THEN T1.POSTAL_CODE 
     ELSE T6.POSTAL_CODE END AS POSTAL_CODE -- Postal Code
,T6.ADDRESS_LINE1_INFO AS ADDRESS_LINE1_INFO
,SUM(T2.GSFS_REPAIR_COUNT) -- GSFS Receipt No Count
 
FROM   `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_REPAIR T1  INNER JOIN (
SELECT	T1.*
	,T2.MAX_TRANSFER_SEQ_NO
	,T2.GSFS_REPAIR_COUNT
	,T2.FRFT_COUNT
	,T2.EFR_PERIOD_DAYS
  FROM `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_MAIN T1
       INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_MAIN_REFERENCE T2
               ON T2.OPERATING_UNIT_ID=T1.OPERATING_UNIT_ID 
              AND T2.GSFS_REPAIR_HEADER_NO=T1.GSFS_REPAIR_HEADER_NO
              AND T2.MAX_TRANSFER_SEQ_NO=T1.TRANSFER_SEQ_NO
              WHERE T1.CORPORATION_ID IN (SELECT CORP_CD FROM COMM.V_OVC_SVC_AUTHORITY WHERE EMPLOYEE_NO = '228494' )
 
) T2 -- ODSI_OT_SERVICE_MAIN
ON (T2.OPERATING_UNIT_ID = T1.OPERATING_UNIT_ID 
AND T2.GSFS_REPAIR_HEADER_NO = T1.GSFS_REPAIR_HEADER_NO 
AND T2.TRANSFER_SEQ_NO = T1.TRANSFER_SEQ_NO) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_SVC_CORP_REGION_HIERARCHY T3 ON (T2.CORPORATION_ID = T3.CORPORATION_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_END_USER T4 ON (T1.END_USER_CODE = T4.END_USER_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SVC_RECEIPT_TYPE T5 ON (T1.RECEIPT_TYPE_CODE = T5.SVC_RECEIPT_TYPE_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OC_I006_MC_ADDRESS_HIST T6 ON (T1.ADDRESS_SEQ_NO = T6.ADDRESS_SEQ_NO) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_DEPARTMENT T7 ON (T1.SERVICE_DEPARTMENT_CODE = T7.SERVICE_DEPARTMENT_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_CENTER_TYPE T8 ON (T7.SVC_CENTER_TYPE_CODE = T8.SERVICE_CENTER_TYPE_CODE) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_ENGINEER T9 ON (T1.SERVICE_ENGINEER_CODE = T9.SERVICE_ENGINEER_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T10 ON (T2.WARRANTY_CLOSING_YYYYMMDD_ID = T10.YYYYMMDD_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T11 ON (T2.ERP_CREATION_YYYYMMDD_ID = T11.YYYYMMDD_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T12 ON (T2.SVC_RECEIPT_YYYYMMDD = T12.YYYYMMDD_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T13 ON (T2.REPAIR_END_YYYYMMDD_ID = T13.YYYYMMDD_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_CUSTOMER T14 ON (T14.OPERATING_UNIT_ID = T2.OPERATING_UNIT_ID 
AND T14.CUSTOMER_CODE = T2.BILL_TO_CUSTOMER_CODE) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_TYPE T15 ON (T2.SERVICE_TYPE_ID = T15.SERVICE_TYPE_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SUBSDR_WARRANTY_TYPE T16 ON (T2.SUBSIDIARY_WARRANTY_TYPE_CODE = T16.SUBSDR_WARRANTY_TYPE_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SVC_PROGRESS_STATUS T17 ON (T2.SVC_PROGRESS_STATUS_ID = T17.SVC_PROGRESS_STATUS_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_DATA_FROM T18 ON (T2.SERVICE_DATA_FROM_ID = T18.SERVICE_DATA_FROM_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_PARTS_HORIZON T19 ON (T2.OPERATING_UNIT_ID = T19.OPERATING_UNIT_ID 
AND T2.GSFS_REPAIR_HEADER_NO = T19.GSFS_REPAIR_HEADER_NO 
AND T2.TRANSFER_SEQ_NO = T19.TRANSFER_SEQ_NO) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EMM_OPERATING_UNIT_ITEM T20 ON (T20.ITEM_ID = T2.ITEM_ID 
AND T20.OPERATING_UNIT_ID = T2.OPERATING_UNIT_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_DIVISION_HIERARCHY T21 ON (T20.SVC_PRODUCT4_ID = T21.PRODUCT4_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_CUSTOMER T22 ON (T2.CUSTOMER_ID = T22.CUSTOMER_ID) INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_B2B_PROJECT T23 ON (T2.PROJECT_ID = T23.PROJECT_ID) LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_MST_STRATEGIC_CITY_FLAG_SHARE T24 ON (T2.OPERATING_UNIT_ID = T24.OPERATING_UNIT_ID AND T2.GSFS_REPAIR_HEADER_NO = T24.GSFS_REPAIR_HEADER_NO AND T2.TRANSFER_SEQ_NO = T24.TRANSFER_SEQ_NO)
WHERE (1=1
AND (1=1
AND (1=1
AND T11.YYYYMM_ID BETWEEN '202508' AND '202607'
AND T18.SERVICE_DATA_FROM_ID IN ('DR')
AND T17.SVC_PROGRESS_STATUS_ID IN ('OPEN')
)
OR (1=1
AND T10.YYYYMM_ID BETWEEN '202508' AND '202607'
AND T18.SERVICE_DATA_FROM_ID IN ('AR')
AND T17.SVC_PROGRESS_STATUS_ID IN ('CLOS','INVC','OPEN')
)
)
AND CASE WHEN T21.DIVISION_ID = 'MST' THEN 'MC' WHEN T21.DIVISION_ID NOT IN ( '<NULL>','<N/A>' ) THEN 'CE' ELSE NULL END IN ('CE')
AND CASE T21.DIVISION_ID WHEN 'PST' THEN 'DS Only' ELSE 'DS Excluded' END IN ('DS Excluded')
AND T8.SERVICE_CENTER_TYPE_NAME IN ('DMS','DSC')
AND T3.CORP_STD1_NAME IN ('LGEID','LGEML','LGESL','LGETH','LGETT','LGEVH','LGEPH')
)
GROUP BY T3.CORP_STD1_NAME,T24.STRATEGIC_CITY_FLAG,T24.STRATEGIC_CITY_NAME,T2.GSFS_REPAIR_HEADER_NO,T21.DIVISION_ID,T21.DIVISION_STD1_NAME,T21.PRODUCT3_STD1_NAME,CASE WHEN T19.PART_NO1 IS NULL THEN 'N' ELSE 'Y' END,T8.SERVICE_CENTER_TYPE_NAME,T23.SHIP_TO_NAME,T22.CUSTOMER_CODE,T14.CUSTOMER_STD1_NAME,RTRIM(T2.BILL_TO_CUSTOMER_CODE)
 
 
,T9.SERVICE_ENGINEER_STD1_NAME,T1.SERVICE_ENGINEER_CODE,CASE WHEN T2.PRC_RECEIPT = 'PR' THEN T16.SUBSDR_WARRANTY_TYPE_ID ELSE T1.WARRANTY_FLAG END,T5.SVC_RECEIPT_TYPE_STD1_NAME,T15.SERVICE_TYPE_ID,T12.YYYY_ID,T12.YYYYMM_ID,T12.YYYYMMDD_ID,FORMAT_DATETIME('%Y%m%d',T1.FIRST_PROMISE_TIMESTAMP),T1.FIRST_PROMISE_TIMESTAMP,FORMAT_DATETIME('%Y%m%d',T1.PROMISE_TIMESTAMP),T1.PROMISE_TIMESTAMP,T1.VISIT_CONFIRM_FLAG,T1.VISIT_CONFIRM_DATE,T13.YYYY_ID,T13.YYYYMM_ID,T13.YYYYMMDD_ID,T11.YYYY_ID,T11.YYYYMM_ID,T2.ERP_CREATION_YYYYMMDD_ID,T2.ERP_CREATION_TIMESTAMP,T22.POSTAL_CODE,T14.POSTAL_CODE,CASE WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) = 0 THEN T4.POSTAL_CODE
     WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.POSTAL_CODE IS NULL THEN T4.POSTAL_CODE
     WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) > 0 THEN T1.POSTAL_CODE 
     ELSE T6.POSTAL_CODE END,T6.ADDRESS_LINE1_INFO