WITH service_product AS (
    SELECT
        SERVICE_PRODUCT_CODE,
        ANY_VALUE(SERVICE_PRODUCT_GROUP_CODE) AS SERVICE_PRODUCT_GROUP_CODE,
        ANY_VALUE(SERVICE_PRODUCT_NAME) AS SERVICE_PRODUCT_NAME
    FROM `pjt-lge-edl-ob`.OB_00105.V_L0GSFS_MC_SERVICE_PRODUCT_CODE
    GROUP BY SERVICE_PRODUCT_CODE
),
service_product_group AS (
    SELECT
        SERVICE_PRODUCT_GROUP_CODE,
        ANY_VALUE(SERVICE_PRODUCT_GROUP_NAME) AS SERVICE_PRODUCT_GROUP_NAME
    FROM `pjt-lge-edl-ob`.OB_00105.V_L0GSFS_MC_SERVICE_PRODUCT_GROUP_CODE
    GROUP BY SERVICE_PRODUCT_GROUP_CODE
),
customer_mst AS (
    SELECT
        CUSTOMER_NO,
        ANY_VALUE(SHIP_TO_CODE) AS SHIP_TO_CODE,
        ANY_VALUE(CUSTOMER_NAME) AS CUSTOMER_NAME
    FROM `pjt-lge-edl-ob`.OB_00105.V_L0GSFS_CN_CUSTOMER_MST_282789_58178
    GROUP BY CUSTOMER_NO
)
SELECT
    'LGEAI' AS SUBSIDIARY_NAME,
    'Atlanta, GA' AS STRATEGIC_CITY_NAME,
    s.SERVICE_ENGINEER_CODE AS SVC_ENGINEER_CODE,
    CAST(NULL AS STRING) AS SVC_ENGINEER_NAME,
    'DMS' AS SERVICE_CENTER_TYPE,
    FORMAT_DATETIME('%Y%m', s.PROMISE_DATE) AS GERP_INPUT_MONTH_YYYYMM_LAST,
    s.MODEL_CODE AS MODEL_CODE,
    CAST(NULL AS STRING) AS SUFFIX_CODE,
    s.SERIAL_NO AS SERIAL_NO,
    CAST(NULL AS NUMERIC) AS PARTS_QTY,
    sp.SERVICE_PRODUCT_GROUP_CODE AS SERVICE_PRODUCT_GROUP_CODE,
    spg.SERVICE_PRODUCT_GROUP_NAME AS SERVICE_PRODUCT_GROUP_NAME,
    s.SERVICE_PRODUCT_CODE AS SERVICE_PRODUCT_CODE,
    sp.SERVICE_PRODUCT_NAME AS SERVICE_PRODUCT_NAME,
    s.DETAIL_SYMPTOM_CODE AS DETAIL_SYMPTOM_CODE,
    s.SERVICE_RECEIPT_NO AS GSFS_RECEIPT_NO,
    FORMAT_DATETIME('%Y%m%d', s.RECEIPT_TIMESTAMP) AS REPAIR_RECEIPT_DATE_YYYYMMDD,
    s.RECEIPT_TIMESTAMP AS REPAIR_RECEIPT_TIMESTAMP,
    CAST(NULL AS STRING) AS REPAIR_END_DATE_YYYYMMDD,
    s.LAST_VISIT_TIMESTAMP AS REPAIR_END_TIMESTAMP,
    s.FIRST_PROMISE_DATE AS FIRST_PROMISE_TIMESTAMP,
    FORMAT_DATETIME('%Y%m%d', s.PROMISE_DATE) AS PROMISE_DATE,
    s.PROMISE_DATE AS PROMISE_TIMESTAMP,
    CAST(NULL AS STRING) AS BILL_TO_CODE,
    CAST(NULL AS STRING) AS BILL_TO_NAME,
    c.SHIP_TO_CODE AS SHIP_TO_CODE,
    CAST(NULL AS STRING) AS PRODUCT3_CODE,
    sp.SERVICE_PRODUCT_GROUP_CODE AS DIVISION_NAME,
    s.SERVICE_TYPE_CODE AS SVC_TYPE_CODE,
    'HS' AS COMPANY_CODE,
    c.CUSTOMER_NAME AS SHIP_TO_FULL_NAME,
    s.SVC_STATUS_CODE AS SVC_STATUS_CODE_GERP,
    'Y' AS STRATEGIC_CITY_FLAG,
    CAST(NULL AS STRING) AS PARTS_NO,
    CAST(NULL AS STRING) AS STRATEGIC_CITY_PHASE,
    s.STATE_NAME AS STATE_NAME,
    s.CITY_NAME AS CITY_NAME,
    'USA' AS COUNTRY_NAME,
    CAST(NULL AS STRING) AS GERP_INPUT_DATE_YYYYMMDD_ID_LAST,
    CAST(NULL AS DATETIME) AS GERP_INPUT_TIMESTAMP_LAST,
    1 AS GSFS_RECEIPT_NO_COUNT,
    CAST(NULL AS NUMERIC) AS PARTS_QTY_1,
    1 AS GSFS_RECEIPT_NO_COUNT_1,
    LPAD(CAST(s.POSTAL_CODE AS STRING), 5, '0') AS POSTAL_CODE,
    s.ADDRESS_LINE1_INFO AS ADDRESS_LINE1_INFO
FROM `pjt-lge-edl-ob`.OB_00105.V_L0GSFS_RW_SERVICE_MST_282789_58177 s
LEFT JOIN service_product sp
    ON s.SERVICE_PRODUCT_CODE = sp.SERVICE_PRODUCT_CODE
LEFT JOIN service_product_group spg
    ON sp.SERVICE_PRODUCT_GROUP_CODE = spg.SERVICE_PRODUCT_GROUP_CODE
LEFT JOIN customer_mst c
    ON s.CUSTOMER_NO = c.CUSTOMER_NO
WHERE FORMAT_DATETIME('%Y%m%d', s.PROMISE_DATE) BETWEEN '{{START_DATE_YYYYMMDD}}' AND '{{END_DATE_YYYYMMDD}}'
  AND s.CORPORATION_CODE = 'LGEAI'
  AND s.SERVICE_TYPE_CODE = 'IH'
  AND s.SVC_CENTER_TYPE_CODE = '02'
  AND sp.SERVICE_PRODUCT_GROUP_CODE IN ('WM', 'REF', 'COK')
  AND LPAD(CAST(s.POSTAL_CODE AS STRING), 5, '0') IN ({{ATLANTA_ZIP_LIST}})
