SELECT
    T21.CORP_STD1_NAME AS SUBSIDIARY_NAME,
    T19.STRATEGIC_CITY_NAME AS STRATEGIC_CITY_NAME,
    T1.SERVICE_ENGINEER_CODE AS SVC_ENGINEER_CODE,
    T6.SERVICE_ENGINEER_STD1_NAME AS SVC_ENGINEER_NAME,
    T24.SERVICE_CENTER_TYPE_NAME AS SERVICE_CENTER_TYPE, -- SVC Center Type
    T7.YYYYMM_ID AS GERP_INPUT_MONTH_YYYYMM_LAST,
    T11.MODEL_CODE AS MODEL_CODE,
    T11.SUFFIX_CODE AS SUFFIX_CODE,
    T2.ITEM_SERIAL_NO AS SERIAL_NO,
    SUM(COALESCE(T14.TOTAL_PARTS_QTY, 0)) AS PARTS_QTY,
    T20.SVC_PRODUCT_GROUP_ID AS SERVICE_PRODUCT_GROUP_CODE,
    T20.SVC_PRODUCT_GROUP_STD1_NAME AS SERVICE_PRODUCT_GROUP_NAME,
    T20.SVC_PRODUCT_ID AS SERVICE_PRODUCT_CODE,
    T20.SVC_PRODUCT_STD1_NAME AS SERVICE_PRODUCT_NAME,
    T1.DETAIL_SYMPTOM_CODE AS DETAIL_SYMPTOM_CODE,
    T2.GSFS_REPAIR_HEADER_NO AS GSFS_RECEIPT_NO,
    T8.YYYYMMDD_ID AS REPAIR_RECEIPT_DATE_YYYYMMDD,
    T1.SVC_RECEIPT_TIMESTAMP AS REPAIR_RECEIPT_TIMESTAMP,
    T9.YYYYMMDD_ID AS REPAIR_END_DATE_YYYYMMDD,
    T1.REPAIR_END_TIMESTAMP AS REPAIR_END_TIMESTAMP,
    T1.FIRST_PROMISE_TIMESTAMP AS FIRST_PROMISE_TIMESTAMP,
    FORMAT_DATETIME('%Y%m%d',T1.PROMISE_TIMESTAMP) AS PROMISE_DATE, -- Promise Date-YYYYMMDD
    T1.PROMISE_TIMESTAMP AS PROMISE_TIMESTAMP,
    RTRIM(T2.BILL_TO_CUSTOMER_CODE) AS BILL_TO_CODE,
    T10.CUSTOMER_STD1_NAME AS BILL_TO_NAME,
    T18.CUSTOMER_CODE AS SHIP_TO_CODE,
    COALESCE(T17.PRODUCT3_ID, T13.PRODUCT3_ID) AS PRODUCT3_CODE,
    T17.DIVISION_STD1_NAME AS DIVISION_NAME,    
    T2.SERVICE_TYPE_ID AS SVC_TYPE_CODE,
    T17.COMPANY_CODE AS COMPANY_CODE,
    T18.CUSTOMER_STD2_NAME AS SHIP_TO_FULL_NAME,
    T2.SVC_PROGRESS_STATUS_ID AS SVC_STATUS_CODE_GERP,
    T19.STRATEGIC_CITY_FLAG AS STRATEGIC_CITY_FLAG,
    T15.BIZ_ITEM_ORIG_ID AS PARTS_NO,
    T19.STRATEGIC_CITY_PHASE AS STRATEGIC_CITY_PHASE,

    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.STATE_NAME)) = 0 THEN '*****'
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.STATE_NAME IS NULL THEN '*****'
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.STATE_NAME)) > 0 THEN T1.STATE_NAME
        ELSE T5.STATE_NAME
    END AS STATE_NAME,

    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.CITY_NAME)) = 0 THEN T4.CITY_NAME
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.CITY_NAME IS NULL THEN T4.CITY_NAME
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.CITY_NAME)) > 0 THEN T1.CITY_NAME
        ELSE T5.CITY_NAME
    END AS CITY_NAME,

    T21.COUNTRY_STD1_NAME AS COUNTRY_NAME,
    T2.ERP_CREATION_YYYYMMDD_ID AS GERP_INPUT_DATE_YYYYMMDD_ID_LAST,
    T2.ERP_CREATION_TIMESTAMP AS GERP_INPUT_TIMESTAMP_LAST,
    T2.GSFS_REPAIR_COUNT AS GSFS_RECEIPT_NO_COUNT,
    COALESCE(T14.TOTAL_PARTS_QTY, 0) AS PARTS_QTY_1,
    SUM(T2.GSFS_REPAIR_COUNT) AS GSFS_RECEIPT_NO_COUNT_1,


    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) = 0 THEN T4.POSTAL_CODE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.POSTAL_CODE IS NULL THEN T4.POSTAL_CODE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) > 0 THEN T1.POSTAL_CODE
        ELSE T5.POSTAL_CODE
    END AS POSTAL_CODE,

    T22.ADDRESS_LINE1_INFO AS ADDRESS_LINE1_INFO

FROM `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_REPAIR T1

INNER JOIN (
    SELECT
        T1.*,
        T2.MAX_TRANSFER_SEQ_NO,
        T2.GSFS_REPAIR_COUNT,
        T2.FRFT_COUNT,
        T2.EFR_PERIOD_DAYS
    FROM `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_MAIN T1
    INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_MAIN_REFERENCE T2
        ON T2.OPERATING_UNIT_ID = T1.OPERATING_UNIT_ID
       AND T2.GSFS_REPAIR_HEADER_NO = T1.GSFS_REPAIR_HEADER_NO
       AND T2.MAX_TRANSFER_SEQ_NO = T1.TRANSFER_SEQ_NO
    WHERE T1.CORPORATION_ID IN (
        SELECT CORP_CD
        FROM COMM.V_OVC_SVC_AUTHORITY
        WHERE EMPLOYEE_NO = '228494'
    )
) T2
    ON T2.OPERATING_UNIT_ID = T1.OPERATING_UNIT_ID
   AND T2.GSFS_REPAIR_HEADER_NO = T1.GSFS_REPAIR_HEADER_NO
   AND T2.TRANSFER_SEQ_NO = T1.TRANSFER_SEQ_NO

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_DATA_FROM T3
    ON T2.SERVICE_DATA_FROM_ID = T3.SERVICE_DATA_FROM_ID

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_END_USER T4
    ON T1.END_USER_CODE = T4.END_USER_ID

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OC_I006_MC_ADDRESS_HIST T5
    ON T1.ADDRESS_SEQ_NO = T5.ADDRESS_SEQ_NO

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_ENGINEER T6
    ON T1.SERVICE_ENGINEER_CODE = T6.SERVICE_ENGINEER_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T7
    ON T2.ERP_CREATION_YYYYMMDD_ID = T7.YYYYMMDD_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T8
    ON T2.SVC_RECEIPT_YYYYMMDD = T8.YYYYMMDD_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T9
    ON T2.REPAIR_END_YYYYMMDD_ID = T9.YYYYMMDD_ID

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_CUSTOMER T10
    ON T10.OPERATING_UNIT_ID = T2.OPERATING_UNIT_ID
   AND T10.CUSTOMER_CODE = T2.BILL_TO_CUSTOMER_CODE

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_ITEM T11
    ON T2.ITEM_ID = T11.ITEM_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_YYYYMMDD T12
    ON T2.WARRANTY_CLOSING_YYYYMMDD_ID = T12.YYYYMMDD_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_PRODUCT3 T13
    ON T2.PRODUCT3_ID = T13.PRODUCT3_ID

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_PARTS T14
    ON T2.OPERATING_UNIT_ID = T14.OPERATING_UNIT_ID
   AND T14.GSFS_REPAIR_HEADER_NO = T2.GSFS_REPAIR_HEADER_NO
   AND T2.TRANSFER_SEQ_NO = T14.TRANSFER_SEQ_NO

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EMM_OPERATING_UNIT_ITEM T15
    ON T14.OPERATING_UNIT_ID = T15.OPERATING_UNIT_ID
   AND T14.ITEM_ID = T15.ITEM_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EMM_OPERATING_UNIT_ITEM T16
    ON T16.ITEM_ID = T2.ITEM_ID
   AND T16.OPERATING_UNIT_ID = T2.OPERATING_UNIT_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_DIVISION_HIERARCHY T17
    ON T16.SVC_PRODUCT4_ID = T17.PRODUCT4_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_CUSTOMER T18
    ON T2.CUSTOMER_ID = T18.CUSTOMER_ID

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_MST_STRATEGIC_CITY_FLAG_SHARE T19
    ON T2.OPERATING_UNIT_ID = T19.OPERATING_UNIT_ID
   AND T2.GSFS_REPAIR_HEADER_NO = T19.GSFS_REPAIR_HEADER_NO
   AND T2.TRANSFER_SEQ_NO = T19.TRANSFER_SEQ_NO

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_SERVICE_PRODUCT T20
    ON T2.SVC_PRODUCT_ID = T20.SVC_PRODUCT_ID

INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_SVC_CORP_REGION_HIERARCHY T21
    ON T2.CORPORATION_ID = T21.CORPORATION_ID

LEFT OUTER JOIN `pjt-lge-edl-ob`.OB_00105.V_L0GSFS_RW_SERVICE_MST_282789_58177 T22
    ON T2.GSFS_REPAIR_HEADER_NO = T22.SERVICE_RECEIPT_NO
    
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_DEPARTMENT T23
    ON T1.SERVICE_DEPARTMENT_CODE = T23.SERVICE_DEPARTMENT_ID

LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_CENTER_TYPE T24
    ON T23.SVC_CENTER_TYPE_CODE = T24.SERVICE_CENTER_TYPE_CODE
    
WHERE 1 = 1
  AND (
        (
            T12.YYYYMM_ID BETWEEN '202601' AND '202602'
            AND T3.SERVICE_DATA_FROM_ID IN ('AR')
        )
        OR
        (
            T7.YYYYMM_ID BETWEEN '202601' AND '202602'
            AND T3.SERVICE_DATA_FROM_ID IN ('DR')
        )
      )
  AND FORMAT_DATETIME('%Y%m%d', T1.PROMISE_TIMESTAMP) BETWEEN '20260101' AND '20260228'
  AND T21.CORP_STD1_NAME IN ('LGEAI')
  AND T3.SERVICE_DATA_FROM_ID IN ('DR')
  AND T2.SERVICE_TYPE_ID = 'IH'
  AND T17.COMPANY_CODE = 'HS'
  AND T19.STRATEGIC_CITY_NAME IS NOT NULL
  AND NOT (T1.ADDRESS_SEQ_NO IS NULL AND (T1.STATE_NAME IS NULL OR TRIM(T1.STATE_NAME) = ''))

GROUP BY
    T21.CORP_STD1_NAME,
    T19.STRATEGIC_CITY_NAME,
    T1.DETAIL_SYMPTOM_CODE,
    T1.SERVICE_ENGINEER_CODE,
    T24.SERVICE_CENTER_TYPE_NAME,
    T6.SERVICE_ENGINEER_STD1_NAME,
    T7.YYYYMM_ID,
    T11.MODEL_CODE,
    T11.SUFFIX_CODE,
    T11.BIZ_ITEM_ORIG_ID,
    T1.PRODUCT_MODEL_CODE,
    T2.ITEM_SERIAL_NO,
    T20.SVC_PRODUCT_GROUP_ID,
    T20.SVC_PRODUCT_GROUP_STD1_NAME,
    T20.SVC_PRODUCT_ID,
    T20.SVC_PRODUCT_STD1_NAME,
    T2.GSFS_REPAIR_HEADER_NO,
    T8.YYYYMMDD_ID,
    T9.YYYYMMDD_ID,
    RTRIM(T2.BILL_TO_CUSTOMER_CODE),
    T10.CUSTOMER_STD1_NAME,
    T15.ITEM_DESCRIPTION,
    T18.CUSTOMER_CODE,
    COALESCE(T17.PRODUCT3_ID, T13.PRODUCT3_ID),
    T17.DIVISION_STD1_NAME,
    T17.COMPANY_CODE,
    T18.CUSTOMER_STD2_NAME,
    T19.STRATEGIC_CITY_FLAG,
    T15.BIZ_ITEM_ORIG_ID,
    T19.STRATEGIC_CITY_PHASE,
    T2.SVC_PROGRESS_STATUS_ID,
    T2.SERVICE_TYPE_ID,

    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.STATE_NAME)) = 0 THEN '*****'
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.STATE_NAME IS NULL THEN '*****'
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.STATE_NAME)) > 0 THEN T1.STATE_NAME
        ELSE T5.STATE_NAME
    END,

    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.CITY_NAME)) = 0 THEN T4.CITY_NAME
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.CITY_NAME IS NULL THEN T4.CITY_NAME
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.CITY_NAME)) > 0 THEN T1.CITY_NAME
        ELSE T5.CITY_NAME
    END,

    T21.COUNTRY_STD1_NAME,
    T2.ERP_CREATION_YYYYMMDD_ID,
    T2.ERP_CREATION_TIMESTAMP,
    T2.GSFS_REPAIR_COUNT,
    COALESCE(T14.TOTAL_PARTS_QTY, 0),

    T1.SVC_RECEIPT_TIMESTAMP,
    T1.REPAIR_END_TIMESTAMP,
    FORMAT_DATETIME('%Y%m%d', T1.PROMISE_TIMESTAMP),
    FORMAT_DATETIME('%Y%m%d', T1.FIRST_PROMISE_TIMESTAMP),
    T1.FIRST_PROMISE_TIMESTAMP,
    T1.PROMISE_TIMESTAMP,

    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) = 0 THEN T4.POSTAL_CODE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.POSTAL_CODE IS NULL THEN T4.POSTAL_CODE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) > 0 THEN T1.POSTAL_CODE
        ELSE T5.POSTAL_CODE
    END,

    T22.ADDRESS_LINE1_INFO;
