SELECT DISTINCT
    T21.CORP_STD1_NAME AS SUBSIDIARY_NAME,
    T19.STRATEGIC_CITY_NAME AS STRATEGIC_CITY_NAME,
    T1.SERVICE_ENGINEER_CODE AS SVC_ENGINEER_CODE,
    T6.SERVICE_ENGINEER_STD1_NAME AS SVC_ENGINEER_NAME,
    T24.SERVICE_CENTER_TYPE_NAME AS SERVICE_CENTER_TYPE,
    T20.SVC_PRODUCT_GROUP_ID AS SERVICE_PRODUCT_GROUP_CODE,
    T20.SVC_PRODUCT_GROUP_STD1_NAME AS SERVICE_PRODUCT_GROUP_NAME,
    T20.SVC_PRODUCT_ID AS SERVICE_PRODUCT_CODE,
    T1.DETAIL_SYMPTOM_CODE AS DETAIL_SYMPTOM_CODE,
    T2.GSFS_REPAIR_HEADER_NO AS GSFS_RECEIPT_NO,
    FORMAT_DATETIME('%Y%m%d', T1.PROMISE_TIMESTAMP) AS PROMISE_DATE,
    T1.PROMISE_TIMESTAMP AS PROMISE_TIMESTAMP,
    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.STATE_NAME)) = 0 THEN '*****'
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.STATE_NAME IS NULL THEN '*****'
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.STATE_NAME)) > 0 THEN T1.STATE_NAME
        ELSE T5.STATE_NAME
    END AS STATE_NAME,
    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.CITY_NAME)) = 0 THEN T4.CITY_NAME
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.CITY_NAME IS NULL THEN T4.CITY_NAME
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.CITY_NAME)) > 0 THEN T1.CITY_NAME
        ELSE T5.CITY_NAME
    END AS CITY_NAME,
    T21.COUNTRY_STD1_NAME AS COUNTRY_NAME,
    CASE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) = 0 THEN T4.POSTAL_CODE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND T1.POSTAL_CODE IS NULL THEN T4.POSTAL_CODE
        WHEN T1.ADDRESS_SEQ_NO IS NULL AND LENGTH(TRIM(T1.POSTAL_CODE)) > 0 THEN T1.POSTAL_CODE
        ELSE T5.POSTAL_CODE
    END AS POSTAL_CODE,
    T22.ADDRESS_LINE1_INFO AS ADDRESS_LINE1_INFO
FROM `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_REPAIR T1
INNER JOIN (
    SELECT
        T1.OPERATING_UNIT_ID,
        T1.GSFS_REPAIR_HEADER_NO,
        T1.TRANSFER_SEQ_NO,
        T1.CORPORATION_ID,
        T1.SERVICE_TYPE_ID,
        T1.ITEM_ID,
        T1.SVC_PRODUCT_ID,
        T1.CUSTOMER_ID,
        T1.BILL_TO_CUSTOMER_CODE
    FROM `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_MAIN T1
    INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OT_SERVICE_MAIN_REFERENCE T2
        ON T2.OPERATING_UNIT_ID = T1.OPERATING_UNIT_ID
       AND T2.GSFS_REPAIR_HEADER_NO = T1.GSFS_REPAIR_HEADER_NO
       AND T2.MAX_TRANSFER_SEQ_NO = T1.TRANSFER_SEQ_NO
    WHERE T1.CORPORATION_ID IN (
        SELECT CORP_CD
        FROM COMM.V_OVC_SVC_AUTHORITY
        WHERE EMPLOYEE_NO = '228494'
    )
) T2
    ON T2.OPERATING_UNIT_ID = T1.OPERATING_UNIT_ID
   AND T2.GSFS_REPAIR_HEADER_NO = T1.GSFS_REPAIR_HEADER_NO
   AND T2.TRANSFER_SEQ_NO = T1.TRANSFER_SEQ_NO
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_END_USER T4
    ON T1.END_USER_CODE = T4.END_USER_ID
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_OC_I006_MC_ADDRESS_HIST T5
    ON T1.ADDRESS_SEQ_NO = T5.ADDRESS_SEQ_NO
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_ENGINEER T6
    ON T1.SERVICE_ENGINEER_CODE = T6.SERVICE_ENGINEER_ID
INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EMM_OPERATING_UNIT_ITEM T16
    ON T16.ITEM_ID = T2.ITEM_ID
   AND T16.OPERATING_UNIT_ID = T2.OPERATING_UNIT_ID
INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_DIVISION_HIERARCHY T17
    ON T16.SVC_PRODUCT4_ID = T17.PRODUCT4_ID
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_MST_STRATEGIC_CITY_FLAG_SHARE T19
    ON T2.OPERATING_UNIT_ID = T19.OPERATING_UNIT_ID
   AND T2.GSFS_REPAIR_HEADER_NO = T19.GSFS_REPAIR_HEADER_NO
   AND T2.TRANSFER_SEQ_NO = T19.TRANSFER_SEQ_NO
INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_SERVICE_PRODUCT T20
    ON T2.SVC_PRODUCT_ID = T20.SVC_PRODUCT_ID
INNER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_ED_SVC_CORP_REGION_HIERARCHY T21
    ON T2.CORPORATION_ID = T21.CORPORATION_ID
LEFT OUTER JOIN `pjt-lge-edl-ob`.OB_00105.V_L0GSFS_RW_SERVICE_MST_282789_58177 T22
    ON T2.GSFS_REPAIR_HEADER_NO = T22.SERVICE_RECEIPT_NO
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_DEPARTMENT T23
    ON T1.SERVICE_DEPARTMENT_CODE = T23.SERVICE_DEPARTMENT_ID
LEFT OUTER JOIN `pjt-lge-edw`.OB_CS_DATA_MART.V_EM_SERVICE_CENTER_TYPE T24
    ON T23.SVC_CENTER_TYPE_CODE = T24.SERVICE_CENTER_TYPE_CODE
WHERE FORMAT_DATETIME('%Y%m%d', T1.PROMISE_TIMESTAMP) BETWEEN '{{START_DATE_YYYYMMDD}}' AND '{{END_DATE_YYYYMMDD}}'
  AND T21.CORP_STD1_NAME IN ('LGEAI')
  AND T2.SERVICE_TYPE_ID IN ('IH')
  AND T17.COMPANY_CODE IN ('HS')
  AND T19.STRATEGIC_CITY_NAME IN ('Atlanta, GA');
